/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.itemMenu;

import DAO.CategoriaDAO;
import DAO.FACTORY.DAOFactory;
import DAO.ItemsMenuDAO;
import DAO.VendedorDAO;
import exceptions.cliente.ClienteNoEncontradoException;
import exceptions.itemMenu.ItemMenuNoEncontradoException;
import gui.ButtonColumn;
import gui.cliente.InterfazClientes;
import gui.pedido.InterfazPedidos;
import gui.vendedores.InterfazVendedores;
import tp.Cliente;
import tp.ItemMenu;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.util.Iterator;
import java.util.List;

/**
 *
 * @author mateo
 */
public class InterfazItemsMenu extends javax.swing.JFrame {

    /**
     * Creates new form InterfazVendedores
     */
    public InterfazItemsMenu() {initComponents();}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BotonVendedores = new javax.swing.JButton();
        BotonItemMenu = new javax.swing.JButton();
        BotonPedidos = new javax.swing.JButton();
        BotonCliente = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaItemsMenu = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        CrearNuevoItemMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BuscadorDeItemMenu = new javax.swing.JTextField();
        BuscarBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(222, 222, 222));

        jPanel2.setBackground(new java.awt.Color(222, 222, 222));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 128)));

        BotonVendedores.setBackground(new java.awt.Color(65, 105, 225));
        BotonVendedores.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BotonVendedores.setText("Vendedores");
        BotonVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVendedoresActionPerformed(evt);
            }
        });

        BotonItemMenu.setBackground(new java.awt.Color(65, 105, 225));
        BotonItemMenu.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BotonItemMenu.setText("ItemMenus");

        BotonPedidos.setBackground(new java.awt.Color(65, 105, 225));
        BotonPedidos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BotonPedidos.setText("Pedidos");
        BotonPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPedidosActionPerformed(evt);
            }
        });

        BotonCliente.setBackground(new java.awt.Color(65, 105, 225));
        BotonCliente.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BotonCliente.setText("Clientes");
        BotonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonVendedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonItemMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonPedidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(BotonVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(BotonItemMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(222, 222, 222));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 128)));

        mostrar(null);
        jScrollPane1.setViewportView(tablaItemsMenu);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(155, 155, 155));
        jTextField1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Lista de Items Menu");

        CrearNuevoItemMenu.setBackground(new java.awt.Color(65, 105, 225));
        CrearNuevoItemMenu.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        CrearNuevoItemMenu.setText("Crear Nuevo ItemMenu");
        CrearNuevoItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearNuevoItemMenuActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(222, 222, 222));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Buscador:");

        BuscadorDeItemMenu.setBackground(new java.awt.Color(222, 222, 222));
        BuscadorDeItemMenu.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        BuscadorDeItemMenu.setForeground(new java.awt.Color(155, 155, 155));

        BuscarBoton.setBackground(new java.awt.Color(65, 105, 225));
        BuscarBoton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BuscarBoton.setText("Buscar");
        BuscarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(CrearNuevoItemMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BuscadorDeItemMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BuscarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BuscarBoton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CrearNuevoItemMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BuscadorDeItemMenu)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void mostrar(String nombre){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Nombre");
        model.addColumn("ID");
        model.addColumn("Nombre Vendedor");
        model.addColumn("Precio");
        model.addColumn("Categoria");
        model.addColumn("Apto Vegano");
        model.addColumn("Apto Celiaco");
        model.addColumn("Editar");
        model.addColumn("Eliminar");

        //Acciones de los botones de la tabla
        Action actionEditar = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JTable table = (JTable) e.getSource();
                int modelRow = Integer.valueOf(e.getActionCommand());

                // Obtiene el ID del item menu desde la tabla en la columna correspondiente
                Object itemMenuId = table.getModel().getValueAt(modelRow, 1); // Columna "ID"

                // Recupera los datos completos del cliente con el ID obtenido
                ItemMenu itemMenu = DAOFactory.getInstance().getItemsMenuDAO().filtrarItemMenuPorId((int) itemMenuId);

                // Crea y muestra una nueva interfaz para editar los datos del cliente
                if (itemMenu != null) {
                    InterfazItemsMenuEditar editarItemMenuInterfaz = new InterfazItemsMenuEditar(itemMenu);
                    editarItemMenuInterfaz.setVisible(true);
                }
            }
        };
        Action actionEliminar = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JTable table = (JTable) e.getSource();
                int modelRow = Integer.valueOf(e.getActionCommand());
                // Obtiene el ID del item Menu desde la tabla en la columna correspondiente
                Object itemMenuId = table.getModel().getValueAt(modelRow, 1); // Columna "ID"

                int confirm = JOptionPane.showConfirmDialog(
                        null,
                        "¿Deseas eliminar el Item Menu?",
                        "Confirmación de eliminación",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE
                );
                if(confirm == JOptionPane.YES_OPTION){

                    try{
                        DAOFactory.getInstance().getItemsMenuDAO().eliminarItemMenu((int) itemMenuId);


                    }catch (ItemMenuNoEncontradoException ex){
                        JOptionPane.showMessageDialog(null,ex.getMessage());
                    }
                }
            };
        };



        if(nombre != null){
            try{
                List<ItemMenu> itemsMenu = DAOFactory.getInstance().getItemsMenuDAO().filtrarItemMenuPorNombre(nombre);
                Iterator<ItemMenu> iterator = itemsMenu.iterator();
                while(iterator.hasNext()){
                    ItemMenu itemMenu = iterator.next();
                    model.addRow(new Object[]{
                            itemMenu.getNombre(),
                            itemMenu.getId(),
                            itemMenu.getVendedor().getNombre(),
                            itemMenu.getPrecio(),
                            itemMenu.getCategoria().getDescripcion(),
                            itemMenu.getAptoVegano(),
                            itemMenu.getAptoCeliaco(),
                    });


                }

            }catch(ClienteNoEncontradoException e){
                JOptionPane.showMessageDialog(null, e.getMessage());

            }
        }
        else{
            try{
                List<Cliente> clientes = DAOFactory.getInstance().getClienteDAO().getClientes();
                Iterator<Cliente> iterator = clientes.iterator();
                while(iterator.hasNext()){
                    Cliente cliente = iterator.next();
                    model.addRow(new Object[]{
                            cliente.getNombre(),
                            cliente.getId(),
                            cliente.getDireccion().getPais(),
                            cliente.getDireccion().getCiudad(),
                            cliente.getDireccion().getCalle(),
                            cliente.getDireccion().getAltura()
                    });


                }

            }catch(ClienteNoEncontradoException e){
                JOptionPane.showMessageDialog(null, e.getMessage());

            }
        }
        // Crear la tabla con el modelo
        tablaItemsMenu.setModel(model);
        ButtonColumn buttonColumnEditar = new ButtonColumn(tablaItemsMenu,actionEditar,6);
        ButtonColumn buttonColumnEliminar = new ButtonColumn(tablaItemsMenu,actionEliminar,7);





    }

    private void BotonVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVendedoresActionPerformed
        // TODO add your handling code here:
        InterfazVendedores interfazVendedores = new InterfazVendedores();
        interfazVendedores.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonVendedoresActionPerformed

    private void CrearNuevoItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearNuevoItemMenuActionPerformed
        // TODO add your handling code here:
        InterfazItemMenuCrear interfazItemMenuCrear = new InterfazItemMenuCrear();
        interfazItemMenuCrear.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CrearNuevoItemMenuActionPerformed

    private void BuscarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarBotonActionPerformed

    private void BotonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonClienteActionPerformed
        // TODO add your handling code here:
        InterfazClientes interfazClientes = new InterfazClientes();
        interfazClientes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonClienteActionPerformed

    private void BotonPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPedidosActionPerformed
        // TODO add your handling code here:
        InterfazPedidos interfazPedidos = new InterfazPedidos();
        interfazPedidos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonPedidosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazItemsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazItemsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazItemsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazItemsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazItemsMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCliente;
    private javax.swing.JButton BotonItemMenu;
    private javax.swing.JButton BotonPedidos;
    private javax.swing.JButton BotonVendedores;
    private javax.swing.JTextField BuscadorDeItemMenu;
    private javax.swing.JButton BuscarBoton;
    private javax.swing.JButton CrearNuevoItemMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tablaItemsMenu;
    // End of variables declaration//GEN-END:variables
}
